  # Statuses
- color: 000000
  name: "Status: Abandoned"
- color: 009700
  name: "Status: Accepted"
- color: bfe5bf
  name: "Status: Available"
- color: e11d21
  name: "Status: Blocked"
- color: 006b75
  name: "Status: Completed"
- color: cccccc
  name: "Status: In Progress"
- color: e11d21
  name: "Status: On Hold"
- color: fef2c0
  name: "Status: Pending"
- color: fbca04
  name: "Status: Review Needed"
- color: e11d21
  name: "Status: Revision Needed"

  # Types
- color: e11d21
  name: "Type: Bug"
- color: fbca04
  name: "Type: Feature"
- color: 84b6eb
  name: "Type: Enhancement"
- color: f1f8ff
  name: "Type: Chore"
- color: cc317c
  name: "Type: Question"

  # Priorities
- color: e11d21
  name: "Priority: Critical"
- color: eb6420
  name: "Priority: High"
- color: fbca04
  name: "Priority: Medium"
- color: 009800
  name: "Priority: Low"
- color: ffffff
  name: "Priority: Minor"

  # Sizes
- color: 009900
  description: Changes 0-9 lines, ignoring generated files
  name: size/XS
- color: 77bb00
  description: Changes 10-29 lines, ignoring generated files
  name: size/S
- color: eebb00
  description: Changes 30-99 lines, ignoring generated files
  name: size/M
- color: ee9900
  description: Changes 100-499 lines, ignoring generated files
  name: size/L
- color: ee5500
  description: Changes 500-999 lines, ignoring generated files
  name: size/XL
- color: ee0000
  description: Changes 1000+ lines, ignoring generated files
  name: size/XXL